/**
 * Created by coder on 2017/2/22.
 */
export const ACTION_SIGN_IN = 'ACTION_SIGN_IN';
export const ACTION_SIGN_OUT = 'ACTION_SIGN_OUT';
export const ACTION_FRESH_TOKEN = 'ACTION_FRESH_TOKEN';
export const ACTION_UPDATE_INFO = 'ACTION_UPDATE_INFO';

export const ACTION_UPDATE_TASK_LISTS = 'ACTION_UPDATE_TASK_LISTS';

export const ACTION_UPDATE_TASK = 'ACTION_UPDATE_TASK';

//更新问答页面
export const ACTION_UPDATE_QUESTION = 'ACTION_UPDATE_QUESTION';
export const ACTION_UPDATE_QUESTION_LISTS = 'ACTION_UPDATE_QUESTION_LISTS';
export const ACTION_DELETE_QUESTION_HISTORY = 'ACTION_DELETE_QUESTION_HISTORY';